spring.application.name=edkart

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/edkart
spring.datasource.username=root
spring.datasource.password=Durai5602.$

spring.web.resources.static-locations=file:uploads/