/**
 * High-Fidelity Banking Database with Image URLs & Admin Records
 */

export const INITIAL_USER = {
  id: 'usr_98124',
  customerId: 'EDK-990142',
  fullName: 'Esakki Durai',
  email: 'durai@edkart.com',
  role: 'USER',
  phone: '+91 98765 43210',
  panNumber: 'ABCDE1234F',
  aadhaarMasked: '•••• •••• 9012',
  dob: '1995-06-15',
  address: 'No. 42, Tech Park Boulevard, Silicon City, Bangalore - 560100',
  kycStatus: 'VERIFIED', // VERIFIED, PENDING, REJECTED
  accountTier: 'Premier Gold Member',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  lastLogin: '2026-09-02T08:30:00Z',
  twoFactorEnabled: true,
  biometricEnabled: true,
  isLocked: false,
};

export const INITIAL_ADMIN = {
  id: 'adm_001',
  customerId: 'EDK-ADMIN-01',
  fullName: 'Bank Operations Administrator',
  email: 'admin@edkart.com',
  role: 'ADMIN',
  phone: '+91 80000 11223',
  avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  department: 'Treasury & Risk Management',
  lastLogin: '2026-09-02T10:00:00Z',
};

export const INITIAL_CUSTOMERS = [
  {
    id: 'usr_98124',
    customerId: 'EDK-990142',
    fullName: 'Esakki Durai',
    email: 'durai@edkart.com',
    phone: '+91 98765 43210',
    panNumber: 'ABCDE1234F',
    kycStatus: 'VERIFIED',
    accountType: 'Premier Savings + Current',
    balance: 1732900.75,
    isLocked: false,
    joinedDate: '2022-01-15',
  },
  {
    id: 'usr_10291',
    customerId: 'EDK-440192',
    fullName: 'Ananya Deshmukh',
    email: 'ananya.d@gmail.com',
    phone: '+91 91234 56789',
    panNumber: 'XYZAB9876C',
    kycStatus: 'PENDING',
    accountType: 'Savings Account',
    balance: 50000.00,
    isLocked: false,
    joinedDate: '2026-08-28',
  },
  {
    id: 'usr_55102',
    customerId: 'EDK-771234',
    fullName: 'Vikramaditya Rao',
    email: 'vikram.rao@enterprise.in',
    phone: '+91 98888 77777',
    panNumber: 'PQRS7788D',
    kycStatus: 'VERIFIED',
    accountType: 'Current Commercial Account',
    balance: 3840000.00,
    isLocked: false,
    joinedDate: '2023-11-10',
  },
  {
    id: 'usr_88201',
    customerId: 'EDK-220199',
    fullName: 'Meera Nambiar',
    email: 'locked@edkart.com',
    phone: '+91 94444 33221',
    panNumber: 'KLMN5544E',
    kycStatus: 'REJECTED',
    accountType: 'Savings Account',
    balance: 12000.00,
    isLocked: true,
    joinedDate: '2026-08-15',
  }
];

export const INITIAL_ACCOUNTS = [
  {
    id: 'acc_sav_01',
    accountNumber: '501009823412',
    accountType: 'Savings Account',
    nickname: 'Primary Wealth Builder',
    balance: 482500.75,
    currency: 'INR',
    status: 'ACTIVE',
    branch: 'Indiranagar Prime Branch, Bangalore',
    ifsc: 'EDKB0001092',
    interestRate: 4.5,
    openedDate: '2022-01-15',
    isPrimary: true,
  },
  {
    id: 'acc_cur_02',
    accountNumber: '502008439120',
    accountType: 'Current Account',
    nickname: 'Business Operations',
    balance: 1250400.00,
    currency: 'INR',
    status: 'ACTIVE',
    branch: 'MG Road Commercial Hub, Bangalore',
    ifsc: 'EDKB0001092',
    interestRate: 0.0,
    openedDate: '2023-04-10',
    isPrimary: false,
  },
  {
    id: 'acc_dep_03',
    accountNumber: '503001298456',
    accountType: 'Fixed Term Deposit',
    nickname: 'High-Yield Growth Vault',
    balance: 750000.00,
    currency: 'INR',
    status: 'ACTIVE',
    branch: 'Indiranagar Prime Branch, Bangalore',
    ifsc: 'EDKB0001092',
    interestRate: 7.25,
    maturityDate: '2027-08-20',
    openedDate: '2024-08-20',
    isPrimary: false,
  }
];

export const INITIAL_TRANSACTIONS = [
  {
    id: 'txn_901',
    referenceId: 'TXN2609028812',
    accountId: 'acc_sav_01',
    type: 'DEBIT',
    category: 'bills',
    amount: 3250.00,
    currency: 'INR',
    date: '2026-09-01T14:20:00Z',
    description: 'Electricity Bill - Tata Power Mumbai',
    status: 'COMPLETED',
    recipient: 'Tata Power Corp',
    fee: 0.0,
    note: 'September Utility Bill',
  },
  {
    id: 'txn_902',
    referenceId: 'TXN2609017734',
    accountId: 'acc_sav_01',
    type: 'CREDIT',
    category: 'salary',
    amount: 175000.00,
    currency: 'INR',
    date: '2026-09-01T09:00:00Z',
    description: 'Monthly Salary Credit - EdKart Tech Solutions',
    status: 'COMPLETED',
    sender: 'EdKart Technologies Pvt Ltd',
    fee: 0.0,
    note: 'Payroll for August 2026',
  },
  {
    id: 'txn_903',
    referenceId: 'TXN2608306612',
    accountId: 'acc_sav_01',
    type: 'DEBIT',
    category: 'transfer',
    amount: 25000.00,
    currency: 'INR',
    date: '2026-08-30T18:45:00Z',
    description: 'IMPS Fund Transfer to Rahul Sharma',
    status: 'COMPLETED',
    recipient: 'Rahul Sharma (HDFC - ••4912)',
    fee: 5.0,
    note: 'Apartment rent advance',
  },
  {
    id: 'txn_904',
    referenceId: 'TXN2608285511',
    accountId: 'acc_cur_02',
    type: 'DEBIT',
    category: 'shopping',
    amount: 45990.00,
    currency: 'INR',
    date: '2026-08-28T11:15:00Z',
    description: 'Apple Store Online - Hardware Equipment',
    status: 'COMPLETED',
    recipient: 'Apple India Retail',
    fee: 0.0,
    note: 'Office dev accessories',
  },
  {
    id: 'txn_905',
    referenceId: 'TXN2608254401',
    accountId: 'acc_sav_01',
    type: 'DEBIT',
    category: 'food',
    amount: 1840.00,
    currency: 'INR',
    date: '2026-08-25T20:30:00Z',
    description: 'Swiggy Gourmet Dining',
    status: 'COMPLETED',
    recipient: 'Swiggy Pay',
    fee: 0.0,
    note: 'Dinner order',
  },
  {
    id: 'txn_906',
    referenceId: 'TXN2608223399',
    accountId: 'acc_sav_01',
    type: 'CREDIT',
    category: 'investment',
    amount: 8750.00,
    currency: 'INR',
    date: '2026-08-22T10:00:00Z',
    description: 'Quarterly FD Interest Yield Payout',
    status: 'COMPLETED',
    sender: 'EdKart Term Deposit Vault',
    fee: 0.0,
    note: 'Q2 Interest Credit',
  },
  {
    id: 'txn_907',
    referenceId: 'TXN2608202288',
    accountId: 'acc_cur_02',
    type: 'DEBIT',
    category: 'bills',
    amount: 1299.00,
    currency: 'INR',
    date: '2026-08-20T16:00:00Z',
    description: 'JioFiber Broadband Ultra High Speed',
    status: 'COMPLETED',
    recipient: 'Reliance Jio Infocomm',
    fee: 0.0,
    note: 'Fiber Internet connection',
  },
  {
    id: 'txn_908',
    referenceId: 'TXN2608181177',
    accountId: 'acc_sav_01',
    type: 'DEBIT',
    category: 'transfer',
    amount: 50000.00,
    currency: 'INR',
    date: '2026-08-18T13:40:00Z',
    description: 'NEFT Transfer to Priya Sundaram',
    status: 'COMPLETED',
    recipient: 'Priya Sundaram (ICICI - ••7721)',
    fee: 0.0,
    note: 'Investment share',
  }
];

export const INITIAL_BENEFICIARIES = [
  {
    id: 'ben_01',
    name: 'Rahul Sharma',
    accountNumber: '91823481234912',
    bankName: 'HDFC Bank',
    ifsc: 'HDFC0000128',
    transferType: 'IMPS/NEFT',
    dailyLimit: 200000,
    status: 'ACTIVE',
    addedDate: '2024-03-12',
    nickname: 'Rahul - Flatmate',
    email: 'rahul.s@gmail.com',
  },
  {
    id: 'ben_02',
    name: 'Priya Sundaram',
    accountNumber: '623910293847721',
    bankName: 'ICICI Bank',
    ifsc: 'ICIC0001099',
    transferType: 'IMPS/NEFT/RTGS',
    dailyLimit: 500000,
    status: 'ACTIVE',
    addedDate: '2024-06-18',
    nickname: 'Priya Sister',
    email: 'priya.sundar@outlook.com',
  },
  {
    id: 'ben_03',
    name: 'EdKart Technologies Vendor',
    accountNumber: '50200843912088',
    bankName: 'EdKart Premier Bank',
    ifsc: 'EDKB0001092',
    transferType: 'INTERNAL',
    dailyLimit: 1000000,
    status: 'ACTIVE',
    addedDate: '2025-01-05',
    nickname: 'Office Vendor Hub',
    email: 'billing@edkart.com',
  },
  {
    id: 'ben_04',
    name: 'Amitabh Verma',
    accountNumber: '30491829381023',
    bankName: 'State Bank of India',
    ifsc: 'SBIN0004012',
    transferType: 'NEFT/RTGS',
    dailyLimit: 150000,
    status: 'ACTIVE',
    addedDate: '2025-08-14',
    nickname: 'Amitabh Consultant',
    email: 'amitabh.v@gmail.com',
  }
];

export const INITIAL_CARDS = [
  {
    id: 'crd_01',
    cardNumber: '4532890123458819',
    cardType: 'CREDIT',
    tier: 'titanium',
    cardName: 'Titanium Elite Credit Card',
    holderName: 'ESAKKI DURAI',
    expiry: '08/29',
    cvv: '921',
    status: 'ACTIVE',
    limitTotal: 500000,
    limitUsed: 84320,
    currency: 'INR',
    domesticOnline: true,
    internationalOnline: false,
    contactless: true,
    atmWithdrawal: true,
    dailyLimit: 100000,
    imageUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'crd_02',
    cardNumber: '5241882390124430',
    cardType: 'DEBIT',
    tier: 'sapphire',
    cardName: 'Sapphire Reserve Platinum Debit',
    holderName: 'ESAKKI DURAI',
    expiry: '11/28',
    cvv: '419',
    status: 'ACTIVE',
    limitTotal: 250000,
    limitUsed: 12450,
    currency: 'INR',
    domesticOnline: true,
    internationalOnline: true,
    contactless: true,
    atmWithdrawal: true,
    dailyLimit: 50000,
    imageUrl: 'https://images.unsplash.com/photo-1589758438368-0ad531db3366?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'crd_03',
    cardNumber: '4091772183901004',
    cardType: 'VIRTUAL',
    tier: 'virtual',
    cardName: 'Virtual Instant Cyber Shield',
    holderName: 'ESAKKI DURAI',
    expiry: '03/30',
    cvv: '762',
    status: 'ACTIVE',
    limitTotal: 100000,
    limitUsed: 3500,
    currency: 'INR',
    domesticOnline: true,
    internationalOnline: true,
    contactless: false,
    atmWithdrawal: false,
    dailyLimit: 25000,
    imageUrl: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600&auto=format&fit=crop&q=80',
  }
];

export const INITIAL_LOANS = [
  {
    id: 'loan_01',
    loanNumber: 'LN-2024-8841',
    loanType: 'Home Mortgage Loan',
    totalPrincipal: 4500000,
    outstandingPrincipal: 3820000,
    interestRate: 8.4,
    tenureMonths: 240,
    monthsPaid: 36,
    monthlyEmi: 38780,
    nextPaymentDate: '2026-09-10',
    status: 'ACTIVE',
    sanctionDate: '2023-08-10',
    collateral: 'Residential Apartment 402, Bangalore',
    imageUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'loan_02',
    loanNumber: 'LN-2025-1029',
    loanType: 'Executive Auto Vehicle Loan',
    totalPrincipal: 1200000,
    outstandingPrincipal: 780000,
    interestRate: 9.1,
    tenureMonths: 60,
    monthsPaid: 21,
    monthlyEmi: 24980,
    nextPaymentDate: '2026-09-15',
    status: 'ACTIVE',
    sanctionDate: '2024-11-15',
    collateral: 'EV Luxury Sedan 2024 Model',
    imageUrl: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=600&auto=format&fit=crop&q=80',
  }
];

export const BANKING_PRODUCTS_CATALOG = [
  {
    id: 'prod_sav_elite',
    category: 'savings',
    name: 'Premier Yield Savings Account',
    tagline: 'Up to 7.0% p.a. interest with zero maintenance fee',
    interestRate: '4.5% - 7.0%',
    minBalance: '₹10,000',
    features: [
      'Unlimited free ATM withdrawals across all banks',
      'Complimentary airport lounge access twice a quarter',
      'Instant cyber fraud insurance cover up to ₹5,00,000',
      'Free Titanium International Debit Card',
    ],
    recommended: true,
    badge: 'Popular Choice',
    imageUrl: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
  },
  {
    id: 'prod_card_titanium',
    category: 'cards',
    name: 'Titanium Elite Metal Credit Card',
    tagline: '5X Reward points on international spends & dining',
    interestRate: '2.49% per month',
    minBalance: 'Annual fee ₹4,999 (Waived on ₹5L spend)',
    features: [
      'Unlimited international lounge access via Priority Pass',
      '10,000 bonus welcome reward points upon activation',
      'Low 1.5% foreign currency markup on cross-border transactions',
      'Dedicated 24/7 concierge & lifestyle manager',
    ],
    recommended: true,
    badge: 'Luxury Metal',
    imageUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
  },
  {
    id: 'prod_loan_home',
    category: 'loans',
    name: 'Smart Home Mortgage Loan',
    tagline: 'Turn your dream home into reality with low EMI rates',
    interestRate: 'Starting at 8.35% p.a.',
    minBalance: 'Tenure up to 30 years',
    features: [
      'Instant digital sanction letter in under 30 minutes',
      'Zero prepayment or foreclosure charges on floating rates',
      'Financing up to 90% of property registration value',
      'Step-down flexible EMI repayment plans',
    ],
    recommended: false,
    badge: 'Lowest Interest',
    imageUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
  },
  {
    id: 'prod_dep_vault',
    category: 'deposits',
    name: 'Fixed Deposit Growth Vault',
    tagline: 'Lock in guaranteed high yields with flexible compounding',
    interestRate: '7.60% p.a. (8.10% for Senior Citizens)',
    minBalance: 'Starting from ₹5,000',
    features: [
      'Premature withdrawal allowed with minimal fee',
      'Monthly, quarterly, or cumulative maturity interest payout',
      'Instant loan/overdraft up to 90% of deposit value',
      'Automated renewal & tax optimization certificates',
    ],
    recommended: true,
    badge: 'Guaranteed Yield',
    imageUrl: 'https://images.unsplash.com/photo-1633158829585-23ba8f7c8caf?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
  },
  {
    id: 'prod_inv_sip',
    category: 'investments',
    name: 'Automated Smart Wealth SIP',
    tagline: 'Diversified institutional portfolios curated by AI algorithms',
    interestRate: '12% - 15% Historic CAGR',
    minBalance: 'Start with ₹1,000 / month',
    features: [
      'Zero commission direct mutual funds & index portfolios',
      'Automated tax-loss harvesting and portfolio rebalancing',
      'Goal-based tracker for retirement, child education & luxury',
      'Instant one-click liquid redemption to savings account',
    ],
    recommended: false,
    badge: 'AI Curated',
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
  },
  {
    id: 'prod_card_sapphire',
    category: 'cards',
    name: 'Sapphire Reserve Rewards Card',
    tagline: 'Comprehensive fuel surcharge waiver & movie privileges',
    interestRate: '2.99% per month',
    minBalance: 'Zero annual fee on joining',
    features: [
      'Buy 1 Get 1 Free movie tickets twice monthly',
      '1% Fuel surcharge waiver across all Indian petrol bunks',
      '1.5% Unlimited cashback on online grocery and utilities',
      'Emergency roadside assistance & lost card insurance',
    ],
    recommended: true,
    badge: 'Top Value',
    imageUrl: 'https://images.unsplash.com/photo-1589758438368-0ad531db3366?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
  }
];

export const INITIAL_TICKETS = [
  {
    id: 'tkt_101',
    ticketNumber: 'TKT-2026-9901',
    customerName: 'Esakki Durai',
    customerId: 'EDK-990142',
    category: 'Transaction Dispute',
    subject: 'Double debit for Swiggy payment Ref: TXN2608254401',
    status: 'IN_PROGRESS', // OPEN, IN_PROGRESS, RESOLVED
    priority: 'HIGH',
    createdAt: '2026-09-01T15:00:00Z',
    messages: [
      { sender: 'customer', text: 'My account was debited twice for order #49102. Please investigate.', timestamp: '2026-09-01T15:00:00Z' },
      { sender: 'admin', text: 'We have initiated reversal request with the merchant gateway.', timestamp: '2026-09-01T16:30:00Z' },
    ]
  },
  {
    id: 'tkt_102',
    ticketNumber: 'TKT-2026-9844',
    customerName: 'Ananya Deshmukh',
    customerId: 'EDK-440192',
    category: 'KYC Document Verification',
    subject: 'PAN card verification delay',
    status: 'OPEN',
    priority: 'NORMAL',
    createdAt: '2026-09-02T07:15:00Z',
    messages: [
      { sender: 'customer', text: 'Submitted PAN copy 2 days ago. Still showing pending.', timestamp: '2026-09-02T07:15:00Z' },
    ]
  },
  {
    id: 'tkt_103',
    ticketNumber: 'TKT-2026-9710',
    customerName: 'Vikramaditya Rao',
    customerId: 'EDK-771234',
    category: 'Card Block / Unblock',
    subject: 'International usage limit enhancement request',
    status: 'RESOLVED',
    priority: 'NORMAL',
    createdAt: '2026-08-25T11:00:00Z',
    messages: [
      { sender: 'customer', text: 'Please increase my daily POS limit to 5 Lakhs for UK travel.', timestamp: '2026-08-25T11:00:00Z' },
      { sender: 'admin', text: 'International limit enhanced to ₹5,00,000 as requested.', timestamp: '2026-08-25T12:15:00Z' },
    ]
  }
];

export const INITIAL_SYSTEM_LOGS = [
  { id: 'log_1', event: 'ADMIN_LOGIN', user: 'admin@edkart.com', ip: '103.12.89.44', status: 'SUCCESS', timestamp: '2026-09-02T10:00:00Z' },
  { id: 'log_2', event: 'FUND_TRANSFER', user: 'durai@edkart.com', ip: '103.12.89.44', status: 'SUCCESS', details: 'Transferred ₹1,000 via IMPS', timestamp: '2026-09-02T09:45:00Z' },
  { id: 'log_3', event: 'FAILED_LOGIN', user: 'locked@edkart.com', ip: '49.207.199.12', status: 'FAILURE', details: '3 Invalid password attempts - Account Auto-Locked', timestamp: '2026-09-02T08:15:00Z' },
  { id: 'log_4', event: 'PRODUCT_RATE_UPDATE', user: 'admin@edkart.com', ip: '103.12.89.44', status: 'SUCCESS', details: 'Updated FD yield to 7.60% p.a.', timestamp: '2026-09-01T14:30:00Z' },
  { id: 'log_5', event: 'KYC_APPROVAL', user: 'admin@edkart.com', ip: '103.12.89.44', status: 'SUCCESS', details: 'Approved KYC for customer EDK-990142', timestamp: '2026-09-01T11:20:00Z' },
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'notif_01',
    category: 'security',
    title: 'New Device Login Detected',
    message: 'Your account was accessed from Chrome on Windows (Silicon City, India). If this was not you, lock your account immediately.',
    timestamp: '2026-09-02T08:30:00Z',
    read: false,
    priority: 'HIGH',
    actionLink: '/security',
  },
  {
    id: 'notif_02',
    category: 'transaction',
    title: 'Salary Credited: ₹1,75,000.00',
    message: 'Monthly salary from EdKart Technologies Pvt Ltd credited to account ••3412.',
    timestamp: '2026-09-01T09:00:00Z',
    read: false,
    priority: 'NORMAL',
    actionLink: '/transactions',
  },
  {
    id: 'notif_03',
    category: 'bills',
    title: 'Electricity Bill Paid Successfully',
    message: 'Paid ₹3,250.00 to Tata Power Mumbai via NetBanking.',
    timestamp: '2026-09-01T14:20:00Z',
    read: true,
    priority: 'LOW',
    actionLink: '/transactions',
  },
  {
    id: 'notif_04',
    category: 'system',
    title: 'Scheduled System Maintenance',
    message: 'Core banking services will undergo routine maintenance on Sunday, Sept 06 between 02:00 AM - 04:00 AM IST.',
    timestamp: '2026-08-29T10:00:00Z',
    read: true,
    priority: 'INFO',
    actionLink: '/support',
  }
];

export const INITIAL_DOCUMENTS = [
  {
    id: 'doc_01',
    title: 'Account Statement - August 2026',
    accountNumber: '501009823412',
    type: 'Monthly Statement (PDF)',
    size: '245 KB',
    date: '2026-08-31',
    status: 'AVAILABLE',
  },
  {
    id: 'doc_02',
    title: 'Annual Interest Certificate FY 2025-26',
    accountNumber: '501009823412',
    type: 'Tax Certificate (PDF)',
    size: '180 KB',
    date: '2026-04-05',
    status: 'AVAILABLE',
  },
  {
    id: 'doc_03',
    title: 'Home Loan Sanction & Amortization Schedule',
    accountNumber: 'LN-2024-8841',
    type: 'Loan Agreement (PDF)',
    size: '1.2 MB',
    date: '2023-08-10',
    status: 'AVAILABLE',
  },
  {
    id: 'doc_04',
    title: 'Fixed Deposit Term Receipt',
    accountNumber: '503001298456',
    type: 'Deposit Receipt (PDF)',
    size: '110 KB',
    date: '2024-08-20',
    status: 'AVAILABLE',
  }
];

export const INITIAL_SESSIONS = [
  {
    id: 'sess_1',
    device: 'Windows 11 PC - Chrome 128',
    location: 'Bangalore, India (Current Session)',
    ip: '103.12.89.44',
    lastActive: 'Active Now',
    isCurrent: true,
  },
  {
    id: 'sess_2',
    device: 'iPhone 15 Pro - EdKart Mobile App',
    location: 'Bangalore, India',
    ip: '49.207.199.12',
    lastActive: 'Yesterday, 10:14 PM',
    isCurrent: false,
  },
  {
    id: 'sess_3',
    device: 'MacBook Pro - Safari 17',
    location: 'Mumbai, India',
    ip: '115.112.45.18',
    lastActive: '28 Aug 2026, 04:30 PM',
    isCurrent: false,
  }
];
